version: '3.8'

services:
  frontend:
    build:
      context: ./bite-swipe-frontend
      dockerfile: Dockerfile
    ports:
      - "4200:3000"
    volumes:
      - ./bite-swipe-frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - API_URL=${API_URL}
    depends_on:
      - backend

  backend:
    build:
      context: ./bite-swipe-backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./bite-swipe-backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - MONGODB_URI=${MONGODB_URI}
      - API_URL=${API_URL}
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - mongodb

  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./bite-swipe-backend/src/seed/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    environment:
      MONGO_INITDB_DATABASE: bite_swipe
    # healthcheck:
    #   test: mongosh --eval "db.adminCommand('ping')"
    #   interval: 10s
    #   timeout: 10s
    #   retries: 5
    #   start_period: 40s


volumes:
  mongodb_data: